"""The combined Free-signal score, and the band it places a Turn in.

Decision 31: the signal combination is *learned from the labelled set* rather
than hand-weighted. `GateModel` is a three-feature logistic regression —
``p_escalate = sigmoid(w . standardise([top_score, margin, sensitive]) + b)`` —
fit on the 550 labelled eval questions (sensitive → should-escalate = 1,
ordinary → should-answer = 0). The fit is full-batch gradient descent from a
zero start with a fixed step count, so it reproduces byte for byte and
`tests/gate/test_calibration_doc.py` re-fits it.

`place` turns `p_escalate` into one of three placements using the committed
**operating point** and **Uncertain band** (`nivara_ai.gate.calibration` chooses
both and records the reasoning in `eval/gate_calibration.md`):

- ``p <= band_lo``  → ``"answer"``  — the Free signals decide, no model call.
- ``p >= band_hi``  → ``"escalate"`` — the Free signals decide, no model call.
- otherwise         → ``"uncertain"`` — and only here does self-consistency run.

The band brackets the operating point; outside it the Free signals alone rule,
which is the property `tests/gate/test_gate.py` asserts.
"""

from __future__ import annotations

import hashlib
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from nivara_ai.gate.signals import SIGNAL_NAMES, FreeSignals

#: The committed model — weights, standardisation, the operating point and the
#: band. Regenerated by `scripts/gate_calibration.py`. Package data (like
#: `turn/system_prompt.md`) rather than a repo-root artifact, because the Gate
#: reads it on the request path and it has to ship inside the deployed image.
MODEL_PATH = Path(__file__).with_name("model.json")

Placement = Literal["answer", "uncertain", "escalate"]


def signal_contributions(
    weights: list[float],
    feature_mean: list[float],
    feature_std: list[float],
    features: list[float],
) -> list[float]:
    """Each standardised signal's additive contribution to the logit —
    `w * (x - mean) / std`. Summed with the bias it gives `p_escalate`; read
    term by term it gives the dominant signal."""

    return [
        w * (x - m) / s
        for w, x, m, s in zip(weights, features, feature_mean, feature_std)
    ]


def escalation_probability(
    weights: list[float],
    bias: float,
    feature_mean: list[float],
    feature_std: list[float],
    features: list[float],
) -> float:
    """`sigmoid(bias + sum of standardised contributions)`. One function so the
    request path (`GateModel`) and the calibration harness (over a
    `LogisticFit`) compute the escalation probability identically."""

    z = bias + sum(signal_contributions(weights, feature_mean, feature_std, features))
    return 1.0 / (1.0 + math.exp(-z))


#: Gradient-descent hyperparameters. Fixed, not tuned — the labelled set is 550
#: rows and three features. The step count is deliberately well past
#: convergence (the gradient norm is ~1e-15 by here), so the fitted weights sit
#: at the machine-precision optimum and a re-fit on another machine reproduces
#: them to more than the six decimals the committed file keeps.
_LEARNING_RATE = 0.2
_STEPS = 20_000
_L2 = 1e-3


@dataclass(frozen=True)
class LogisticFit:
    weights: list[float]
    bias: float
    feature_mean: list[float]
    feature_std: list[float]


def train_weights(features: list[list[float]], labels: list[int]) -> LogisticFit:
    """Deterministic logistic regression on standardised features.

    No `numpy.random`, no shuffling — the row order is the caller's and the
    start is all-zeros, so two runs over the same table produce identical
    weights.
    """

    import numpy as np

    x = np.asarray(features, dtype=np.float64)
    y = np.asarray(labels, dtype=np.float64)
    mean = x.mean(axis=0)
    std = x.std(axis=0)
    std[std == 0.0] = 1.0
    xs = (x - mean) / std

    n, d = xs.shape
    w = np.zeros(d)
    b = 0.0
    for _ in range(_STEPS):
        z = xs @ w + b
        p = 1.0 / (1.0 + np.exp(-z))
        error = p - y
        w -= _LEARNING_RATE * (xs.T @ error / n + _L2 * w)
        b -= _LEARNING_RATE * float(error.mean())

    return LogisticFit(
        weights=[float(v) for v in w],
        bias=float(b),
        feature_mean=[float(v) for v in mean],
        feature_std=[float(v) for v in std],
    )


@dataclass(frozen=True)
class GateModel:
    weights: list[float]
    bias: float
    feature_mean: list[float]
    feature_std: list[float]
    #: The answer/escalate threshold on `p_escalate` the sweep chose.
    operating_point: float
    #: The Uncertain band `(lo, hi)`, `lo <= operating_point <= hi`.
    band_lo: float
    band_hi: float
    #: Hash of the calibration signal table these were fit against — a changed
    #: Corpus or labelled set moves it and the drift test fails.
    calibration_sha: str

    # -- prediction ----------------------------------------------------------

    def _contributions(self, signals: FreeSignals) -> list[float]:
        return signal_contributions(
            self.weights, self.feature_mean, self.feature_std, signals.as_features()
        )

    def p_escalate(self, signals: FreeSignals) -> float:
        return escalation_probability(
            self.weights, self.bias, self.feature_mean, self.feature_std,
            signals.as_features(),
        )

    def place(self, p_escalate: float) -> Placement:
        if p_escalate <= self.band_lo:
            return "answer"
        if p_escalate >= self.band_hi:
            return "escalate"
        return "uncertain"

    def dominant_signal(self, signals: FreeSignals) -> str:
        """Which Free signal pushed `p_escalate` up the most — used to pick the
        escalation reason (`sensitive_question` vs `low_retrieval_confidence`)
        for a hard escalate."""

        contributions = dict(zip(SIGNAL_NAMES, self._contributions(signals)))
        return max(contributions, key=contributions.get)

    # -- persistence -------------------------------------------------------

    def to_dict(self) -> dict:
        return {
            "signal_names": list(SIGNAL_NAMES),
            "weights": [round(w, 6) for w in self.weights],
            "bias": round(self.bias, 6),
            "feature_mean": [round(v, 6) for v in self.feature_mean],
            "feature_std": [round(v, 6) for v in self.feature_std],
            "operating_point": round(self.operating_point, 6),
            "band_lo": round(self.band_lo, 6),
            "band_hi": round(self.band_hi, 6),
            "calibration_sha": self.calibration_sha,
        }

    @classmethod
    def from_dict(cls, data: dict) -> GateModel:
        if list(data.get("signal_names", [])) != list(SIGNAL_NAMES):
            raise ValueError(
                f"gate model signal order {data.get('signal_names')!r} does not match "
                f"{SIGNAL_NAMES!r} — the weights would be transposed"
            )
        return cls(
            weights=list(data["weights"]),
            bias=data["bias"],
            feature_mean=list(data["feature_mean"]),
            feature_std=list(data["feature_std"]),
            operating_point=data["operating_point"],
            band_lo=data["band_lo"],
            band_hi=data["band_hi"],
            calibration_sha=data["calibration_sha"],
        )

    def save(self, path: Path = MODEL_PATH) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), indent=2) + "\n")


def load_gate_model(path: Path = MODEL_PATH) -> GateModel:
    return GateModel.from_dict(json.loads(path.read_text()))


def table_sha(feature_rows: list[list[float]]) -> str:
    payload = "\n".join(",".join(f"{v:.6f}" for v in row) for row in feature_rows)
    return hashlib.sha256(payload.encode()).hexdigest()[:16]
