"""The pre-chat disclosure (ticket 25, user story 8, decision 51).

A Visitor gets to decide what to say with the facts in front of them, so before
the first message the widget shows a notice that names:

- the **free-tier model provider(s)** a Turn's answer may be generated by —
  read from `nivara_ai.model.chain.CHAIN`, the same list the failover chain
  runs, so the notice cannot claim a different provider than the one that
  answers;
- the **trace vendor** a Turn's Trace is sent to — read from
  `nivara_ai.observability.vendor.FREE_TIER`;
- that messages **may be used for model improvement** by those providers on
  their free tiers;
- a request **not to enter personal information**.

`build_disclosure` assembles it from those sources; `GET /widget/disclosure`
serves it. `tests/widget/test_disclosure.py` asserts every required element is
present and that the provider list matches the chain.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Disclosure:
    #: The provider display names, in chain order, deduplicated.
    model_providers: list[str]
    #: The trace vendor and its plan, e.g. "Langfuse Cloud (Hobby)".
    trace_vendor: str
    #: The full notice text, ready to render above the chat input.
    text: str

    def as_dict(self) -> dict:
        return {
            "model_providers": self.model_providers,
            "trace_vendor": self.trace_vendor,
            "text": self.text,
        }


_PROVIDER_DISPLAY = {
    "groq": "Groq",
    "gemini": "Google Gemini",
}


def _provider_names() -> list[str]:
    from nivara_ai.model.chain import CHAIN

    seen: list[str] = []
    for spec in CHAIN:
        name = _PROVIDER_DISPLAY.get(spec.rung.provider, spec.rung.provider.title())
        if name not in seen:
            seen.append(name)
    return seen


def build_disclosure() -> Disclosure:
    from nivara_ai.observability.vendor import FREE_TIER

    providers = _provider_names()
    vendor = f"{FREE_TIER.vendor} ({FREE_TIER.plan})"

    provider_phrase = _join(providers)
    text = (
        f"This is a demo. Your messages are answered by a language model running on "
        f"a free tier from {provider_phrase}, and the details of each exchange are "
        f"sent to {vendor} so the team can review how the assistant did. On these "
        f"free tiers your messages may be used to improve the providers' models. "
        f"Please don't enter personal information — no full names, account numbers, "
        f"card numbers, or anything you wouldn't want retained. A real question "
        f"about your account can still go to a person; just ask."
    )
    return Disclosure(model_providers=providers, trace_vendor=vendor, text=text)


def _join(items: list[str]) -> str:
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + f" and {items[-1]}"
