"""The Scenario inventory: the hand-authored spine everything measurable
is generated from (ticket 07).

The Corpus (ticket 08) and the eval questions (ticket 09) are generated
from a `Scenario` in separate passes and never from each other, so a
question and the document that answers it share a situation rather than a
vocabulary. This module only loads and validates the committed inventory;
it does not generate anything from it.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Literal

from pydantic import BaseModel

#: Sensitive is a property of the *question* a Scenario gives rise to —
#: money movement, fraud, KYC — never a property of an endpoint, because
#: Nivara Desk has no capability of any of those kinds.
ScenarioCategory = Literal["ordinary", "sensitive"]

#: The closed set of situations the inventory groups by, read off
#: `scenarios/counts.md` — a Scenario's topic is never free text.
ScenarioTopic = Literal[
    "account-configuration",
    "account-recovery-ownership",
    "api-integrations",
    "billing-disputes",
    "billing-invoicing",
    "data-export-import",
    "fraudulent-communications",
    "incidents-outages",
    "payment-method-changes",
    "reporting-analytics",
    "seats-plan-management",
    "sso-authentication",
    "suspicious-account-activity",
]

#: The repo root, resolved from this file so it is found the same way
#: whether the package is installed or run from a clone.
_REPO_ROOT = Path(__file__).resolve().parents[3]

#: The committed inventory, one JSON object per line so it diffs cleanly
#: and a generator can stream it. Sibling to `recordings/` at the repo
#: root — both are committed artifacts rather than code.
DEFAULT_INVENTORY_PATH = _REPO_ROOT / "scenarios" / "inventory.jsonl"

#: Where `render_counts` is committed. Generated rather than hand-edited —
#: `scripts/scenario_counts.py` writes it, and a test regenerates and
#: compares so it cannot drift from the inventory it describes.
COUNTS_PATH = _REPO_ROOT / "scenarios" / "counts.md"


class Scenario(BaseModel):
    """One situation a support layer meets, hand-authored and tagged.

    `situation` carries enough detail for the Corpus generator and the
    eval-question generator to each produce something concrete without
    reading the other's output — it names who is affected, what
    triggered the situation and what they want, but is neither a
    document nor a question itself.
    """

    id: str
    category: ScenarioCategory
    topic: ScenarioTopic
    situation: str


def load_scenarios(path: Path = DEFAULT_INVENTORY_PATH) -> list[Scenario]:
    scenarios = [
        Scenario.model_validate_json(line)
        for line in path.read_text().splitlines()
        if line.strip()
    ]
    ids = [s.id for s in scenarios]
    duplicates = [id_ for id_, count in Counter(ids).items() if count > 1]
    if duplicates:
        raise ValueError(f"duplicate Scenario ids: {sorted(duplicates)}")
    return scenarios


def counts_by_category(scenarios: list[Scenario]) -> dict[str, int]:
    return dict(sorted(Counter(s.category for s in scenarios).items()))


def counts_by_topic(scenarios: list[Scenario]) -> dict[str, int]:
    return dict(sorted(Counter(s.topic for s in scenarios).items()))


def render_counts(scenarios: list[Scenario]) -> str:
    """The text `scripts/scenario_counts.py` writes to `COUNTS_PATH`.

    Lives here rather than in the script, alongside `counts_by_category`
    and `counts_by_topic` — one function, so the script and the test that
    checks `COUNTS_PATH` for drift cannot disagree about what the counts
    file should say.
    """

    lines = [
        "# Scenario counts",
        "",
        "Generated by `python scripts/scenario_counts.py` from "
        "`scenarios/inventory.jsonl`. Do not hand-edit.",
        "",
        f"Total: {len(scenarios)}",
        "",
        "## By category",
        "",
    ]
    lines += [f"- {category}: {count}" for category, count in counts_by_category(scenarios).items()]

    lines += ["", "## By topic", ""]
    lines += [f"- {topic}: {count}" for topic, count in counts_by_topic(scenarios).items()]

    lines.append("")
    return "\n".join(lines)
